# --------------------------------------------
[[generator.randomfloat64]]
    id = "float"

[[generator.randomint64]]
    id = "int"

[[serializer.template]]
    id = "lineprotocol"
    template = """
foo value={{ float }},value2={{ int }}
foo value={{ float }},value2={{ int }}
foo value={{ float }},value2={{ int }}
"""

[[serializer.template]]
    id = "json"
    template = """
{ "foo": {{ int }} }
"""

[[output.stdout]]
    serializers = ["lineprotocol"]

[[output.stderr]]
    serializers = ["json"]
